#!/bin/bash

# assign variables

ACTION=${1}

Version=${1.0.1}

function create_file() {

function delete_file() {
        -c | --delete Delete_file

touch "${1}-12345"
delete "${1}-12345"
}

function display_help() {

function delete_file()  {

cat << EOF
Usage: ${0} {-c|--create|-h|--help} <filename>
       ${0} {-d|--delete|} <foo>-12345 <server>-12345
       ${0} {-v|--version|} 
OPTIONS:
        -c | --create Create a new file
        -h | --help Display the command help
        -d | --delete Delete file

Examples:
        Create a new file:
                $ ${0} -c foo.txt
        Display help:
                $ ${0} -h
        Delete file:
                $ ${0} -d foo

function delete_file() {
        -c | --delete Delete_file
EOF
}

case "$ACTION" in
        -h|--help)
                display_help
                ;;
        -c|--create)
                create_file "${2:-server}"
                ;;
        -d|--delete)
                delete_file "${2:-server}"

         *)
         echo "Usage ${0} {-c|-h}"
         echo "Delete ${2} {-d}"
         exit 1
esac
